### PR TITLE
upload pootle translations

### PR DESCRIPTION
**Pull request by g1039**

### CODE REVIEW

**Comment by g1039** [comment]
This PR is not ready for review. Still waiting for **Urdu (India)** and **Assamese (India)** translations to be updated in Pootle.

**Comment by TrevorOctober** [comment]
@saeedmb8 Ready for review

**Comment by g1039** [comment]
@saeedmb8 Ready for review

**Comment by g1039** [comment]
@saeedmb8 Please review

**Comment by g1039** [comment]
:+1: from @saeedmb8

**Pull request merged**
